-- Relay core schema. Flyway owns the schema; JPA entities map onto these tables.

CREATE TABLE workflow (
    id          VARCHAR(128) PRIMARY KEY,
    name        VARCHAR(256) NOT NULL,
    description TEXT,
    status      VARCHAR(32)  NOT NULL,
    definition  JSONB        NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE TABLE run (
    run_id              VARCHAR(64) PRIMARY KEY,
    workflow_id         VARCHAR(128) NOT NULL REFERENCES workflow (id),
    definition_snapshot JSONB        NOT NULL,
    status              VARCHAR(32)  NOT NULL,
    trigger_type        VARCHAR(32)  NOT NULL,
    input               JSONB        NOT NULL,
    current_node_id     VARCHAR(128),
    steps_executed      INTEGER      NOT NULL DEFAULT 0,
    ai_tokens_used      INTEGER      NOT NULL DEFAULT 0,
    error               JSONB,
    started_at          TIMESTAMPTZ  NOT NULL,
    finished_at         TIMESTAMPTZ
);
CREATE INDEX idx_run_workflow ON run (workflow_id);
CREATE INDEX idx_run_status ON run (status);

CREATE TABLE step (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id            VARCHAR(64)  NOT NULL REFERENCES run (run_id),
    node_id           VARCHAR(128) NOT NULL,
    node_type         VARCHAR(64)  NOT NULL,
    sequence          INTEGER      NOT NULL,
    status            VARCHAR(32)  NOT NULL,
    attempt           INTEGER      NOT NULL DEFAULT 1,
    resolved_input    JSONB,
    output            JSONB,
    tokens_prompt     INTEGER,
    tokens_completion INTEGER,
    idempotency_key   VARCHAR(256),
    started_at        TIMESTAMPTZ  NOT NULL,
    duration_ms       INTEGER,
    CONSTRAINT uq_step_run_sequence UNIQUE (run_id, sequence)
);
CREATE INDEX idx_step_run_sequence ON step (run_id, sequence);

CREATE TABLE approval (
    id         VARCHAR(64) PRIMARY KEY,
    run_id     VARCHAR(64)  NOT NULL REFERENCES run (run_id),
    node_id    VARCHAR(128) NOT NULL,
    message    TEXT         NOT NULL,
    status     VARCHAR(32)  NOT NULL,
    decided_by VARCHAR(256),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_approval_run ON approval (run_id);
CREATE INDEX idx_approval_status ON approval (status);

-- Durable queue mirror: Redis is the primary queue, but every job is also persisted here so
-- a crashed worker's in-flight work is recoverable and delayed jobs survive a restart.
CREATE TABLE queue_job (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id       VARCHAR(64) NOT NULL REFERENCES run (run_id),
    status       VARCHAR(32) NOT NULL,
    available_at TIMESTAMPTZ NOT NULL,
    leased_until TIMESTAMPTZ,
    attempts     INTEGER     NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_queue_job_dispatch ON queue_job (status, available_at);
CREATE INDEX idx_queue_job_run ON queue_job (run_id);
